banksite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('mainapp.urls'))
]

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('customers/', views.customerView, name='customer'),
    path('transactions/', views.transactionView, name='transaction'),
    path('transfer/', views.transferView, name='transfer'),
    path('transfer/confirm/', views.confirmTransferView, name='confirm'),
]

mainapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Customer(models.Model):
    acc_number = models.PositiveBigIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    balance = models.PositiveBigIntegerField()


    def __str__(self):
        return str(self.acc_number)

class Transaction(models.Model):
    acc_number = models.ForeignKey(Customer, on_delete=models.CASCADE)
    trans_amount = models.PositiveBigIntegerField()
    time = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=10)

    
    def __str__(self):
        return str(self.time)

banksite/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

mainapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from mainapp.models import Customer, Transaction
from django.db import connection

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

def customerView(request):
    data = Customer.objects.raw('SELECT * FROM public.mainapp_customer ORDER BY acc_number ASC')
    mydict = {'customers':data}
    return render(request, 'customer.html', context=mydict)

def transactionView(request):
    data = Transaction.objects.raw('SELECT * FROM public.mainapp_transaction ORDER BY time DESC')
    mydict = {'transactions':data}
    return render(request, 'transactions.html', context=mydict)

def transferView(request):

    if request.method == 'POST':
        acc_number_1 = request.POST['acc_number_1']
        acc_number_2 = request.POST['acc_number_2']

        data_one = Customer.objects.filter(acc_number=acc_number_1)
        data_two = Customer.objects.filter(acc_number=acc_number_2)

        if data_one and data_two:
            request.session['acc_number_1'] = acc_number_1
            request.session['acc_number_2'] = acc_number_2

            s_data = Customer.objects.raw('SELECT * FROM public.mainapp_customer WHERE acc_number={}'.format(acc_number_1))
            r_data = Customer.objects.raw('SELECT * FROM public.mainapp_customer WHERE acc_number={}'.format(acc_number_2))

            my_dict = {'s_data':s_data, 'r_data':r_data}

            return render(request, 'confirm_transfer.html', context=my_dict)

        else:
            if not data_one:
                message = 'Invalid Sender A/C Number, Please Check'
            else:
                message = 'Invalid Receiver A/C Number, Please Check'

            my_msg_dict = {'message':message}
            return render(request, 'transfer.html', context=my_msg_dict)

    return render(request, 'transfer.html')


def confirmTransferView(request):
    acc_number_1 = request.session['acc_number_1']
    acc_number_2 = request.session['acc_number_2']

    data1 = Customer.objects.filter(acc_number=acc_number_1).values()

    print(data1)

    sender_bal = int(data1[0]['balance'])

    if request.method == 'POST':

        amount = int(request.POST['amount'])

        if amount > sender_bal:
            message = 'Insufficient Balance'
            
            my_error_dict = {'message':message}
            return render(request, 'transfer.html', context=my_error_dict)
        else:
            with connection.cursor() as c:
                c.execute('CALL public.stored_procedure({},{},{})'.format(acc_number_1,acc_number_2,amount))
            message = 'Transaction Successful'

            my_success_dict = {'message':message}
            return render(request, 'index.html', context=my_success_dict)
    return render(request, 'confirm_transfer.html')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liberty Bank</title>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style="background:#0e1112">
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static 'images/brand_image1.png' %}" alt="" style="width: 220px; height: 40px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:customer' %}">Customers_data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:transfer' %}">Transfers_data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:transaction' %}">Transactions_data</a>
                </li>
                </ul>
            </div>
        </div>
    </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer style="background:#1a2324">
        <p>Developed by <a class='footer-name' href="#">Rishi Devanpalli</a> | 2021 All rights reserved.</p>
    </footer>
</body>
</html>

templates/confirm_transfer.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container">

    <h1 style="margin-top: 25px; color:aliceblue; margin-bottom: 25px;">Kindly Check the Details!</h1>

    <table style="margin-left: auto; margin-right: auto; margin-top: 30px; border-collapse: separate; border-spacing: 100px 0;">
        <tr>
            <td>
                <div class="card bg-light mb-3" style="width: 22rem;">
                    <div class="card-header">Sender</div>
                    <div class="card-body">
                        {% for info in s_data %}
                        <p class="card-text"><b>A/C Number: </b>{{ info.acc_number }}</p>
                        <p class="card-text"><b>Name: </b>{{ info.name }}</p>
                        <p class="card-text"><b>Email: </b>{{ info.email }}</p>
                        <p class="card-text"><b>Balance: </b>{{ info.balance }}</p>
                        {% endfor %}
                    </div>
                </div>
            </td>
            <td>
                <div class="card bg-light mb-3" style="width: 22rem;">
                    <div class="card-header">Receiver</div>
                    <div class="card-body">
                        {% for info in r_data %}
                        <p class="card-text"><b>A/C Number: </b>{{ info.acc_number }}</p>
                        <p class="card-text"><b>Name: </b>{{ info.name }}</p>
                        <p class="card-text"><b>Email Id: </b>{{ info.email }}</p>
                        <p class="card-text"><b>Balance: </b>{{ info.balance }}</p>
                        {% endfor %}
                    </div>
                </div>
            </td>
        </tr>
    </table>

    <br><br>

    <form method="POST" style="margin-left: 30%; margin-right: 30%; color:aliceblue" action="confirm/">
        {% csrf_token %}
        <div class="row g-3 align-items-center">
            <div class="col-auto">
              <label for="amount" class="col-form-label">Amount</label>
            </div>
            <div class="col-auto">
              <input type="number" id="amount" class="form-control" aria-describedby="amountHelp" name="amount" min="1" required>
            </div>
            <div class="col-auto">
              <span id="amountHelp" class="form-text">
                Please enter carefully
              </span>
            </div>
        </div>

        <br>

        <input type="submit" value="Transfer" class="btn btn-primary" style="margin-left: 40%; margin-right: 40%;">

        <br>

    </form>

</div>

{% if message %}

    <script>
        alert('{{ message }}');
    </script>

{% endif %}

{% endblock %}

templates/customer.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <h1 style="margin-top: 25px; color:aliceblue; margin-bottom: 25px;">Customer Database</h1>

    <div class="container">

    {% if customers %}
    <table class="table" style="color:aliceblue">
        <thead>
            <tr>
                <th scope="col">A/C Number</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Balance</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
            <tr>
                <th scope="row">{{ customer.acc_number }}</th>
                <td>{{ customer.name }}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.balance }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}

        <h3>No Data Found!</h3>
        
    {% endif %}

    </div>
    
    {% endblock %}
    

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}


<img src="{% static 'images/background.jpg' %}" alt="">

{% if message %}

    <script>
        alert('{{ message }}');
    </script>

{% endif %}
    
{% endblock %}

templates/transactions.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <h1 style="text-align: center; margin-top: 25px; color:aliceblue; margin-bottom: 25px;">Transaction Database</h1>

    <div class="container">

    {% if transactions %}
    <table class="table" style="color:aliceblue">
        <thead>
            <tr>
                <th scope="col">Timestamp</th>
                <th scope="col">A/C Number</th>
                <th scope="col">Transacted Amount</th>
                <th scope="col">Description</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <th scope="row">{{ transaction.time }}</th>
                <td>{{ transaction.acc_number_id }}</td>
                <td>{{ transaction.trans_amount }}</td>
                <td>{{ transaction.description }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}

        <h3>No Data Found!</h3>
        
    {% endif %}

    </div>
    
{% endblock %}

templates/transfer.html
{% extends 'base.html' %}

{% block content %}


    <h1 style="margin-top: 25px; color:aliceblue; margin-bottom: 25px;">Transfer money</h1>

    <div class="container">

    <form method="POST" style="color:aliceblue">
        {% csrf_token %}
        <div class="mb-3">
          <label for="acc_number_1" class="form-label">Sender A/C Number</label>
          <input type="number" class="form-control" id="acc_number_1" name="acc_number_1" required>
        </div>
        <div class="mb-3">
          <label for="acc_number_2" class="form-label">Receiver A/C Number</label>
          <input type="number" class="form-control" id="acc_number_2" name="acc_number_2" required>
        </div>
        <input type="submit" value="Fetch Details" class="btn btn-primary">
    </form>

    </div>

    {% if message %}

      <script>
        alert('{{ message }}');
      </script>

    {% endif %}
    
{% endblock %}